services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      - REACT_APP_URL=http://localhost:3001/api
    depends_on:
      - backend
  backend:
    build: /backend
    ports:
      - 3001:3001